/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AddrLine2 model module.
* @module model/AddrLine2
* @version 1.0.0
*/
export default class AddrLine2 {
    /**
    * Constructs a new <code>AddrLine2</code>.
    * @alias module:model/AddrLine2
    * @class
    * @param addrLine2 {String} 
    */

    constructor(addrLine2) {
        
        
        this['addrLine2'] = addrLine2;
        
    }

    /**
    * Constructs a <code>AddrLine2</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddrLine2} obj Optional instance to populate.
    * @return {module:model/AddrLine2} The populated <code>AddrLine2</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddrLine2();
                        
            
            if (data.hasOwnProperty('addrLine2')) {
                obj['addrLine2'] = ApiClient.convertToType(data['addrLine2'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} addrLine2
    */
    'addrLine2' = undefined;




}
