/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AddrLine1 model module.
* @module model/AddrLine1
* @version 1.0.0
*/
export default class AddrLine1 {
    /**
    * Constructs a new <code>AddrLine1</code>.
    * @alias module:model/AddrLine1
    * @class
    * @param addrLine1 {String} 
    */

    constructor(addrLine1) {
        
        
        this['addrLine1'] = addrLine1;
        
    }

    /**
    * Constructs a <code>AddrLine1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddrLine1} obj Optional instance to populate.
    * @return {module:model/AddrLine1} The populated <code>AddrLine1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddrLine1();
                        
            
            if (data.hasOwnProperty('addrLine1')) {
                obj['addrLine1'] = ApiClient.convertToType(data['addrLine1'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} addrLine1
    */
    'addrLine1' = undefined;




}
