/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The City model module.
* @module model/City
* @version 1.0.0
*/
export default class City {
    /**
    * Constructs a new <code>City</code>.
    * @alias module:model/City
    * @class
    * @param city {String} 
    */

    constructor(city) {
        
        
        this['city'] = city;
        
    }

    /**
    * Constructs a <code>City</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/City} obj Optional instance to populate.
    * @return {module:model/City} The populated <code>City</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new City();
                        
            
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} city
    */
    'city' = undefined;




}
