/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Dob model module.
* @module model/Dob
* @version 1.0.0
*/
export default class Dob {
    /**
    * Constructs a new <code>Dob</code>.
    * @alias module:model/Dob
    * @class
    * @param dob {String} 
    */

    constructor(dob) {
        
        
        this['dob'] = dob;
        
    }

    /**
    * Constructs a <code>Dob</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Dob} obj Optional instance to populate.
    * @return {module:model/Dob} The populated <code>Dob</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dob();
                        
            
            if (data.hasOwnProperty('dob')) {
                obj['dob'] = ApiClient.convertToType(data['dob'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} dob
    */
    'dob' = undefined;




}
