/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Email model module.
* @module model/Email
* @version 1.0.0
*/
export default class Email {
    /**
    * Constructs a new <code>Email</code>.
    * @alias module:model/Email
    * @class
    * @param email {String} 
    */

    constructor(email) {
        
        
        this['email'] = email;
        
    }

    /**
    * Constructs a <code>Email</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Email} obj Optional instance to populate.
    * @return {module:model/Email} The populated <code>Email</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Email();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    'email' = undefined;




}
