/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FirstName model module.
* @module model/FirstName
* @version 1.0.0
*/
export default class FirstName {
    /**
    * Constructs a new <code>FirstName</code>.
    * @alias module:model/FirstName
    * @class
    * @param firstName {String} 
    */

    constructor(firstName) {
        
        
        this['firstName'] = firstName;
        
    }

    /**
    * Constructs a <code>FirstName</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FirstName} obj Optional instance to populate.
    * @return {module:model/FirstName} The populated <code>FirstName</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FirstName();
                        
            
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} firstName
    */
    'firstName' = undefined;




}
