/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LastName model module.
* @module model/LastName
* @version 1.0.0
*/
export default class LastName {
    /**
    * Constructs a new <code>LastName</code>.
    * @alias module:model/LastName
    * @class
    * @param lastName {String} 
    */

    constructor(lastName) {
        
        
        this['lastName'] = lastName;
        
    }

    /**
    * Constructs a <code>LastName</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LastName} obj Optional instance to populate.
    * @return {module:model/LastName} The populated <code>LastName</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastName();
                        
            
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} lastName
    */
    'lastName' = undefined;




}
