/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LoanAmount model module.
* @module model/LoanAmount
* @version 1.0.0
*/
export default class LoanAmount {
    /**
    * Constructs a new <code>LoanAmount</code>.
    * @alias module:model/LoanAmount
    * @class
    * @param loanAmount {String} 
    */

    constructor(loanAmount) {
        
        
        this['loanAmount'] = loanAmount;
        
    }

    /**
    * Constructs a <code>LoanAmount</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoanAmount} obj Optional instance to populate.
    * @return {module:model/LoanAmount} The populated <code>LoanAmount</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanAmount();
                        
            
            if (data.hasOwnProperty('loanAmount')) {
                obj['loanAmount'] = ApiClient.convertToType(data['loanAmount'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} loanAmount
    */
    'loanAmount' = undefined;




}
