/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PhoneNumber model module.
* @module model/PhoneNumber
* @version 1.0.0
*/
export default class PhoneNumber {
    /**
    * Constructs a new <code>PhoneNumber</code>.
    * @alias module:model/PhoneNumber
    * @class
    * @param phoneNumber {String} 
    */

    constructor(phoneNumber) {
        
        
        this['phoneNumber'] = phoneNumber;
        
    }

    /**
    * Constructs a <code>PhoneNumber</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PhoneNumber} obj Optional instance to populate.
    * @return {module:model/PhoneNumber} The populated <code>PhoneNumber</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PhoneNumber();
                        
            
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} phoneNumber
    */
    'phoneNumber' = undefined;




}
