/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The State model module.
* @module model/State
* @version 1.0.0
*/
export default class State {
    /**
    * Constructs a new <code>State</code>.
    * @alias module:model/State
    * @class
    * @param state {String} 
    */

    constructor(state) {
        
        
        this['state'] = state;
        
    }

    /**
    * Constructs a <code>State</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/State} obj Optional instance to populate.
    * @return {module:model/State} The populated <code>State</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new State();
                        
            
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} state
    */
    'state' = undefined;




}
