/**
 * API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import AddrLine1 from '../model/AddrLine1';
import AddrLine2 from '../model/AddrLine2';
import City from '../model/City';
import Dob from '../model/Dob';
import Email from '../model/Email';
import FirstName from '../model/FirstName';
import InlineResponse200 from '../model/InlineResponse200';
import LastName from '../model/LastName';
import LoanAmount from '../model/LoanAmount';
import PhoneNumber from '../model/PhoneNumber';
import State from '../model/State';
import Zip from '../model/Zip';

/**
* Applicants service.
* @module api/ApplicantsApi
* @version 1.0.0
*/
export default class ApplicantsApi {

    /**
    * Constructs a new ApplicantsApi. 
    * @alias module:api/ApplicantsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the lookupApplicant operation.
     * @callback module:api/ApplicantsApi~lookupApplicantCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns public information about a loan applicant
     * See publicly available financial info about a loan applicant including credit score, based on name, address and date of birth
     * @param {Object} opts Optional parameters
     * @param {module:api/ApplicantsApi~lookupApplicantCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse200}
     */
    lookupApplicant(firstName, lastName, addrLine1, city, state, zip, dob, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'firstName': firstName,
        'lastName': lastName,
        'addrLine1': addrLine1,
        'addrLine2': opts['addrLine2'],
        'city': city,
        'state': state,
        'zip': zip,
        'dob': dob,
        'email': opts['email'],
        'phoneNumber': opts['phoneNumber'],
        'loanAmount': opts['loanAmount']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/api/v1/lookup-applicant', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
