/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AcqualifyApiDocumentation);
  }
}(this, function(expect, AcqualifyApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AcqualifyApiDocumentation.InlineResponse200();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse200', function() {
    it('should create an instance of InlineResponse200', function() {
      // uncomment below and update the code to test InlineResponse200
      //var instane = new AcqualifyApiDocumentation.InlineResponse200();
      //expect(instance).to.be.a(AcqualifyApiDocumentation.InlineResponse200);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new AcqualifyApiDocumentation.InlineResponse200();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new AcqualifyApiDocumentation.InlineResponse200();
      //expect(instance).to.be();
    });

    it('should have the property applicant (base name: "applicant")', function() {
      // uncomment below and update the code to test the property applicant
      //var instane = new AcqualifyApiDocumentation.InlineResponse200();
      //expect(instance).to.be();
    });

  });

}));
