/**
 * Acqualify API Documentation
 * The Acqualify API provides services to mortgage brokers and realtors to help applicants qualify for loans.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AddrLine1 from './model/AddrLine1';
import AddrLine2 from './model/AddrLine2';
import City from './model/City';
import Dob from './model/Dob';
import Email from './model/Email';
import FirstName from './model/FirstName';
import InlineResponse200 from './model/InlineResponse200';
import LastName from './model/LastName';
import LoanAmount from './model/LoanAmount';
import PhoneNumber from './model/PhoneNumber';
import State from './model/State';
import Zip from './model/Zip';
import ApplicantsApi from './api/ApplicantsApi';

/**
* The_Acqualify_API_provides_services_to_mortgage_brokers_and_realtors_to_help_applicants_qualify_for_loans_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AcqualifyApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new AcqualifyApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AcqualifyApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AcqualifyApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AcqualifyApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddrLine1 model constructor.
     * @property {module:model/AddrLine1}
     */
    AddrLine1,

    /**
     * The AddrLine2 model constructor.
     * @property {module:model/AddrLine2}
     */
    AddrLine2,

    /**
     * The City model constructor.
     * @property {module:model/City}
     */
    City,

    /**
     * The Dob model constructor.
     * @property {module:model/Dob}
     */
    Dob,

    /**
     * The Email model constructor.
     * @property {module:model/Email}
     */
    Email,

    /**
     * The FirstName model constructor.
     * @property {module:model/FirstName}
     */
    FirstName,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The LastName model constructor.
     * @property {module:model/LastName}
     */
    LastName,

    /**
     * The LoanAmount model constructor.
     * @property {module:model/LoanAmount}
     */
    LoanAmount,

    /**
     * The PhoneNumber model constructor.
     * @property {module:model/PhoneNumber}
     */
    PhoneNumber,

    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State,

    /**
     * The Zip model constructor.
     * @property {module:model/Zip}
     */
    Zip,

    /**
    * The ApplicantsApi service constructor.
    * @property {module:api/ApplicantsApi}
    */
    ApplicantsApi
};
