/*
 * API Documentation
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@creditsaint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ApplicantsApi();
  });

  describe('(package)', function() {
    describe('ApplicantsApi', function() {
      describe('lookupApplicant', function() {
        it('should call lookupApplicant successfully', function(done) {
          // TODO: uncomment, update parameter values for lookupApplicant call
          /*
          var firstName = "firstName_example";
          var lastName = "lastName_example";
          var addrLine1 = "addrLine1_example";
          var city = "city_example";
          var state = "state_example";
          var zip = 789;
          var dob = "dob_example";
          var opts = {};
          opts.addrLine2 = "addrLine2_example";
          opts.email = "email_example";
          opts.phoneNumber = "phoneNumber_example";
          opts.loanAmount = "loanAmount_example";

          instance.lookupApplicant(firstName, lastName, addrLine1, city, state, zip, dob, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
